link:
  img_sidebar: "http://placehold.it/160x160"
validate:
  name:
    length: 40
  email:
    length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    length: 6
  number_min: 0
  title:
    length: 200
  content:
    length: 5000
session:
  remember: "1"
user:
  per_page: 10
request:
  per_page: 6
format_date: "%d-%m-%Y"
