link:
  img_sidebar: "http://placehold.it/160x160"
validate:
  name:
    length: 40
  email:
    length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    length_min: 8
    length_max: 30
    regex: !ruby/regexp '/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])/i'
  number_min: 0
  title:
    length: 200
  content:
    length: 5000
session:
  remember: "1"
user:
  per_page: 10
  role: 2
  group: 1
  role_manager: 3
request:
  per_page: 6
  aasm_search: {"Pending": "pending", "Approve": "approve", "Paid": "paid", "Rejected": "rejected"}
  type_paid: 0
  type_rejected: 1
income:
  per_page: 6
format_date: "%d-%m-%Y"
min_value: 0
limit_request: 3
limit_noti: 5
